export const LOG_EVENTS = {
  // Request lifecycle
  REQUEST_START: 'REQUEST_START',
  REQUEST_END: 'REQUEST_END',

  // Auth events
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',
  HMAC_VERIFIED: 'HMAC_VERIFIED',
  HMAC_REJECTED: 'HMAC_REJECTED',

  // Domain events - Chat
  QUOTA_CHECKED: 'QUOTA_CHECKED',
  QUOTA_DEDUCTED: 'QUOTA_DEDUCTED',
  QUOTA_EXHAUSTED: 'QUOTA_EXHAUSTED',
  MESSAGE_STORED: 'MESSAGE_STORED',
  AI_REQUEST_START: 'AI_REQUEST_START',
  AI_REQUEST_END: 'AI_REQUEST_END',

  // Domain events - Subscriptions
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  RENEWAL_ATTEMPTED: 'RENEWAL_ATTEMPTED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',

  // Security events
  RATE_LIMIT_HIT: 'RATE_LIMIT_HIT',
  INVALID_CONTENT_TYPE: 'INVALID_CONTENT_TYPE',
  OVERSIZED_BODY: 'OVERSIZED_BODY',
  TIMEOUT: 'TIMEOUT',
  RBAC_DENIED: 'RBAC_DENIED',
  RBAC_ALLOWED: 'RBAC_ALLOWED',

  // System events
  SERVER_STARTED: 'SERVER_STARTED',
  DB_CONNECTED: 'DB_CONNECTED',
  GRACEFUL_SHUTDOWN: 'GRACEFUL_SHUTDOWN',
  KEYPAIR_GENERATED: 'KEYPAIR_GENERATED',
  KEYPAIR_LOADED: 'KEYPAIR_LOADED',
} as const;

export type LogEvent = (typeof LOG_EVENTS)[keyof typeof LOG_EVENTS];

export const LOG_MODULES = {
  CHAT: 'chat',
  SUBSCRIPTIONS: 'subscriptions',
  AUTH: 'auth',
  SYSTEM: 'system',
  MIDDLEWARE: 'middleware',
} as const;

export type LogModule = (typeof LOG_MODULES)[keyof typeof LOG_MODULES];
